// Sample data and constants for DecisionTrail

export const DEFAULT_PROJECTS = [
  { id: 'proj-1', name: 'Greenfield MRF Installation', client: 'Metro Waste Solutions', status: 'active', createdAt: '2026-01-15' },
  { id: 'proj-2', name: 'Conveyor Line Retrofit', client: 'Pacific Recycling Corp', status: 'active', createdAt: '2026-03-01' },
  { id: 'proj-3', name: 'Optical Sorter Upgrade', client: 'Tri-County Disposal', status: 'completed', createdAt: '2025-10-20' },
];

export const SAMPLE_DECISIONS = [
  {
    id: 'dec-001', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Selected 45mm sorting screen mesh size instead of the originally specified 38mm opening.',
    why: 'Site testing showed the 38mm mesh clogged within 4 hours with the local waste stream composition. The client operations manager and senior technician agreed 45mm provides better throughput while still capturing target material grades.',
    alternatives: 'Considered 50mm mesh (rejected because it would miss too much valuable PET) and a dual-layer 38/50mm screen (rejected due to $18K additional cost and 3-week lead time).',
    who: 'Mike Torres (Senior Technician), Sarah Chen (Client Ops Manager), Ajith Srikanth (Field Coordinator)',
    risks: 'Slightly lower capture rate for small PET containers. Will monitor output quality during first two weeks of commissioning.',
    phase: 'Installation', category: 'Engineering', impact: 'High',
    summary: 'Changed sorting screen mesh from 38mm to 45mm based on site testing',
    createdAt: '2026-04-12T14:30:00Z', completeness: 100,
  },
  {
    id: 'dec-002', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Rerouted the main conveyor belt path to avoid the existing stormwater drainage line discovered during excavation.',
    why: 'Excavation on Day 3 revealed an unmapped 12-inch stormwater pipe running directly under the planned conveyor foundation. Relocating the pipe would require city permits (6-8 week delay) and $25K in civil work.',
    alternatives: 'Option A: relocate the stormwater pipe (rejected, 6-8 week permit delay). Option B: bridge over the pipe with a raised foundation (rejected, structural engineer flagged load concerns).',
    who: 'Dave Park (Site Supervisor), Lisa Nguyen (Structural Engineer), City Inspector',
    risks: 'New route adds 8 feet to conveyor length, increasing belt tension. Motor sizing to be reviewed by engineering before procurement.',
    phase: 'Installation', category: 'Engineering', impact: 'Critical',
    summary: 'Rerouted conveyor path to avoid unmapped stormwater drainage line',
    createdAt: '2026-04-08T09:15:00Z', completeness: 100,
  },
  {
    id: 'dec-003', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Switched motor supplier from GreenDrive to ABB for the primary sorting drum drive.',
    why: 'GreenDrive quoted a 14-week lead time that would push past the commissioning deadline. ABB can deliver an equivalent 75kW motor in 6 weeks at a 12% cost premium.',
    alternatives: 'Considered WEG motors (similar lead time to ABB but no local service center) and refurbished GreenDrive units (warranty concerns).',
    who: 'Procurement Team, Ajith Srikanth, Project Manager',
    risks: 'ABB motor has slightly different mounting dimensions; mounting plate adapter needed ($800, 1-week fabrication).',
    phase: 'Procurement', category: 'Vendor', impact: 'High',
    summary: 'Switched drum drive motor supplier from GreenDrive to ABB',
    createdAt: '2026-03-22T16:45:00Z', completeness: 100,
  },
  {
    id: 'dec-004', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Delayed commissioning start by one week to complete electrical safety inspection.',
    why: 'The third-party electrical inspector found two junction boxes without proper NFPA labeling. Fixes take 2-3 days but the next available inspection slot is in 7 days.',
    alternatives: 'Considered requesting an expedited re-inspection (inspector unavailable) and proceeding with partial commissioning of non-electrical systems (rejected due to integrated safety interlock requirements).',
    who: 'Electrical Contractor, Safety Officer, Client PM',
    risks: 'One-week delay pushes final handover date. Client notified and accepted revised timeline.',
    phase: 'Commissioning', category: 'Safety', impact: 'High',
    summary: 'Delayed commissioning one week for electrical safety re-inspection',
    createdAt: '2026-05-01T11:20:00Z', completeness: 100,
  },
  {
    id: 'dec-005', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Added a second shift for conveyor installation to recover lost schedule days.',
    why: 'Rain delays in Week 2 cost three working days. Adding a second shift for five days recovers the schedule without extending the project end date.',
    alternatives: 'Weekend overtime only (would recover only 2 of 3 days). Accepting the delay (client rejected due to downstream equipment delivery dates).',
    who: 'Site Supervisor, Field Crew Lead, Client PM',
    risks: 'Second shift increases labor costs by approximately $12K. Fatigue management protocol required for crews.',
    phase: 'Installation', category: 'Scheduling', impact: 'Medium',
    summary: 'Added second shift to recover three rain delay days',
    createdAt: '2026-04-18T08:00:00Z', completeness: 100,
  },
  {
    id: 'dec-006', projectId: 'proj-2', projectName: 'Conveyor Line Retrofit',
    what: 'Selected roller bearings from SKF instead of original Timken spec for the return idlers.',
    why: 'SKF units are rated for higher contamination environments and have sealed housings that reduce maintenance frequency from quarterly to semi-annual.',
    alternatives: 'Keeping Timken (lower upfront cost but higher maintenance). NSK sealed bearings (comparable performance but 8-week lead time).',
    who: 'Maintenance Manager, Procurement Lead',
    risks: 'Different bearing dimensions require new mounting brackets. Retrofit adds half a day per idler station.',
    phase: 'Procurement', category: 'Engineering', impact: 'Medium',
    summary: 'Switched return idler bearings from Timken to SKF sealed units',
    createdAt: '2026-04-25T13:10:00Z', completeness: 100,
  },
  {
    id: 'dec-007', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Approved client request to add a secondary magnetic separator at the end of the sorting line.',
    why: 'Client wants to capture ferrous metals that pass through the primary separator, increasing metal recovery revenue by an estimated 8%.',
    alternatives: '',
    who: 'Client Engineering Director',
    risks: 'Scope addition adds $32K and 4 days to installation.',
    phase: 'Installation', category: 'Scope', impact: 'High',
    summary: 'Added secondary magnetic separator per client scope change request',
    createdAt: '2026-04-20T10:30:00Z', completeness: 80,
  },
  {
    id: 'dec-008', projectId: 'proj-2', projectName: 'Conveyor Line Retrofit',
    what: 'Decided to perform conveyor belt splice during the scheduled plant shutdown window rather than requesting a separate outage.',
    why: 'Plant operations cannot afford a second unscheduled shutdown. The 48-hour maintenance window during the July 4th holiday provides enough time.',
    alternatives: '',
    who: 'Plant Manager, Project Coordinator',
    risks: '',
    phase: 'Planning', category: 'Scheduling', impact: 'Medium',
    summary: 'Aligned belt splice work with planned July 4th plant shutdown',
    createdAt: '2026-05-10T15:00:00Z', completeness: 60,
  },
  {
    id: 'dec-009', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Allocated $5K contingency reserve for potential sensor recalibration during commissioning.',
    why: 'NIR optical sensors may need recalibration once processing real waste stream material versus test samples used during factory acceptance.',
    alternatives: 'Not allocating reserve (risk of unbudgeted expense if calibration needed). Requesting vendor to include on-site calibration in contract (vendor declined).',
    who: 'Project Manager, Finance Lead',
    risks: 'If not needed, funds return to project budget. If exceeded, requires change order.',
    phase: 'Planning', category: 'Budget', impact: 'Low',
    summary: 'Set aside $5K contingency for NIR sensor recalibration',
    createdAt: '2026-03-15T14:00:00Z', completeness: 100,
  },
  {
    id: 'dec-010', projectId: 'proj-1', projectName: 'Greenfield MRF Installation',
    what: 'Hired two additional temporary electricians for the final wiring phase.',
    why: 'Current crew of three cannot complete 200+ termination points within the 10-day window before commissioning starts.',
    alternatives: 'Extending the wiring phase by one week (rejected, pushes commissioning). Subcontracting to local electrical firm (rejected, unfamiliar with equipment-specific wiring standards).',
    who: 'Electrical Lead, HR Coordinator, Site Supervisor',
    risks: 'Temporary staff need two days of equipment-specific orientation before productive work begins.',
    phase: 'Installation', category: 'Resource', impact: 'Medium',
    summary: 'Added two temporary electricians for final wiring push',
    createdAt: '2026-04-28T09:45:00Z', completeness: 100,
  },
];

export const AI_PROMPTS = {
  what: {
    key: 'what',
    label: 'What was decided?',
    prompt: "What happened? Describe the decision in your own words, like you're telling a colleague.",
    placeholder: 'e.g., "We switched the mesh size on the sorting screen from 38mm to 45mm after testing showed it was clogging..."',
    required: true,
  },
  why: {
    key: 'why',
    label: 'Why was this decided?',
    prompt: "What was the reasoning? What problem were you solving or what drove this choice?",
    placeholder: 'e.g., "The 38mm mesh was clogging every 4 hours with the waste composition at this site..."',
    required: true,
  },
  alternatives: {
    key: 'alternatives',
    label: 'Other options considered?',
    prompt: "Were there other options on the table? What made you go a different direction?",
    placeholder: 'e.g., "We looked at 50mm mesh but it would miss too much PET. Also considered a dual-layer screen but it was $18K more..."',
    required: false,
  },
  who: {
    key: 'who',
    label: 'Who was involved?',
    prompt: "Who was part of this decision? Names, roles, or teams.",
    placeholder: 'e.g., "Mike Torres (senior tech), Sarah Chen (client ops manager), and myself"',
    required: false,
  },
  risks: {
    key: 'risks',
    label: 'Any risks or trade-offs?',
    prompt: "Anything to watch out for? Trade-offs the team should know about?",
    placeholder: 'e.g., "Slightly lower capture rate for small containers. We will monitor output quality during commissioning."',
    required: false,
  },
};

export const PROMPT_ORDER = ['what', 'why', 'alternatives', 'who', 'risks'];
